sudo: required
language: rust
rust: stable
services:
  - docker

branches:
  except:
    - gh-pages

script:
  - cargo test
  - cargo doc

after_success:
  - docker run -it --rm --security-opt seccomp=unconfined --volume "$PWD:/volume" -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID"  elmtai/docker-rust-kcov  "cargo-kcov kcov -v --coveralls"
  - bash deploy-docs.sh

deploy:
  provider: script
  script: bash -e ./deploy.sh
  on:
    tags: true
