sudo: false
language: rust
rust: 1.5.0
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

branches:
  except:
    - gh-pages

script:
  - cargo test
  - cargo doc

after_success:
  - export PATH=$PATH:$HOME/kcov/bin
  - bash install-kcov.sh
  - kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo --exclude-path=tests target/kcov target/debug/map_ut-*
  - kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo --exclude-path=tests target/kcov target/debug/set_ut-*
  - kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo --exclude-path=tests target/kcov target/debug/tst-*
  - bash deploy-docs.sh
